spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://42.192.81.74:3306/wxmanage?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 3
    minidle: 3
    maxActive: 18
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual
    filters: stat,wall,log4j
server:
  port: 9966
  servlet:
    context-path: /wx/manage
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mappers/*.xml

